set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" *********************************************
" PLUGINS
" *********************************************
" Repos vundle :
" https://vimawesome.com/
" *********************************************
Plugin 'VundleVim/Vundle.vim'

Plugin 'jelera/vim-javascript-syntax'
Plugin 'maksimr/vim-jsbeautify'
Plugin 'crusoexia/vim-monokai'
" I - Arbol de directorios izq
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'jistr/vim-nerdtree-tabs'
" F - Arbol de directorios izq
" I - Barra inferior con info
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
" Añade info sobre git
Plugin 'tpope/vim-fugitive'
" F - Barra inferior con info
Plugin 'posva/vim-vue'
Plugin 'vim-syntastic/syntastic'
Plugin 'mtscout6/syntastic-local-eslint.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
set number
syntax on
colorscheme monokai
set t_Co=256  " vim-monokai now only support 256 colours in terminal.
set tabstop=2 
set shiftwidth=2
set softtabstop=2 
set expandtab
set encoding=utf-8
set mouse:a

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_javascript_eslint_exe = 'npm run lint --'

" Si necesitas abrir el arbol cuando se abra vim
" au VimEnter *  NERDTree

map <c-f> :call JsBeautify()<cr>
map <C-b> :NERDTreeToggle<CR>

" Si necesitas abrir el arbol cuando se abra vim
"let g:nerdtree_tabs_open_on_console_startup=1
let g:airline#extensions#tabline#enabled = 1
set clipboard=unnamedplus
