#!/bin/bash

id=$(xinput list|grep TouchPad|grep 'id=[[:digit:]][[:digit:]]'|grep -o '[[:digit:]][[:digit:]]') ;
xinput list|grep TouchPad ;
echo "Input id: $id disabled" ;
xinput set-prop $id "Device Enabled" 0 ;
